// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cred.query.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCred = `-- name: CreateCred :one
INSERT INTO creds (user_id, cred_name, resume_url, video_url)
VALUES 
($1, $2, $3, $4) 
RETURNING id, user_id, cred_name, resume_url, video_url
`

type CreateCredParams struct {
	UserID    pgtype.UUID
	CredName  string
	ResumeUrl string
	VideoUrl  string
}

func (q *Queries) CreateCred(ctx context.Context, arg CreateCredParams) (Cred, error) {
	row := q.db.QueryRow(ctx, createCred,
		arg.UserID,
		arg.CredName,
		arg.ResumeUrl,
		arg.VideoUrl,
	)
	var i Cred
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredName,
		&i.ResumeUrl,
		&i.VideoUrl,
	)
	return i, err
}
