// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cred struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CredName  string
	ResumeUrl string
	VideoUrl  string
}

type User struct {
	ID             pgtype.UUID
	Email          string
	Name           string
	ProfilePicture pgtype.Text
	Clerkid        pgtype.Text
}
