// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.query.sql

package storage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, profile_picture, clerkId)
VALUES ($1, $2, $3, $4) RETURNING id, email, name, profile_picture, clerkid
`

type CreateUserParams struct {
	Name           string
	Email          string
	ProfilePicture pgtype.Text
	Clerkid        pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.ProfilePicture,
		arg.Clerkid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.ProfilePicture,
		&i.Clerkid,
	)
	return i, err
}
